<<<<<<< HEAD
houssem:
    resource: "@houssemBundle/Controller/"
    type:     annotation
=======
produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
>>>>>>> rahma
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation

