<?php

namespace houssemBundle\Repository;

/**
 * blogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBycategorie()
    {
        $Query=$this->getEntityManager()->createQuery(
            "SELECT a.nom , COUNT(c.id) as st
             from houssemBundle:blog c INNER JOIN houssemBundle:categorie a 
             WHERE c.categorie = a.id
              GROUP BY a.nom"
        );
        return $Query->getArrayResult();
    }

}
